### PR TITLE
Bump `pear/pear_exception` version.

### LINKED ISSUE #14: Bump `pear/pear_exception` version to 1.0.1
Can we bump the `pear/pear_exception` version to the current release/stable of 1.0.1. 

I've tested this locally and can't find any obvious compatibility issues that this would introduce.

### PR DESCRIPTION
**Pull request by MikeyMJCO**
Fixes #14

### CODE REVIEW

**Comment by jparise** [comment]
It looks like the CI build identified a test failure. Is this caused by this change?

**Comment by ashnazg** [comment]
No, the Travis failures look like build config issues... looks like the 5.4 and 5.5 build configs need to be updated based on Travis itself changing the way it does things over time.

**Comment by MikeyMJCO** [comment]
This is probably pertinent:

> PHP 5.2(.x) - 5.3(.x) support is available on Precise only #
> We do not support these versions on Trusty or Xenial or Bionic. If you need to test them, please use Precise.
> 
> PHP 5.4(.x) - 5.5(.x) support is available on Precise and Trusty only #
> We do not support these versions on Xenial or Bionic. If you need to test them, please use Precise or Trusty.
> 
> PHP 5.6(.x) - 7.0(.x) support is available on Precise, Trusty and Xenial only #
> We do not support these versions on Bionic. If you need to test them, please use Precise or Trusty or Xenial.
> 
> PHP 7.4(.x) onwards support is available on Trusty, Xenial and Bionic only #
> We do not support these versions on Precise. If you need to test them, please use Trusty, Xenial, or Bionic.

_Source:_ https://docs.travis-ci.com/user/languages/php/

**Comment by MikeyMJCO** [comment]
@jparise are you able to cut a release with this fix in it by any chance?

**Comment by jparise** [comment]
> @jparise are you able to cut a release with this fix in it by any chance?

I’d like the get the CI checks fixed first.

**Comment by MikeyMJCO** [comment]
> > @jparise are you able to cut a release with this fix in it by any chance?
> 
> I’d like to get the CI checks fixed first.

Anything I can do to help on that score?

**Comment by jparise** [comment]
> > > @jparise are you able to cut a release with this fix in it by any chance?
> 
> > 
> 
> > I’d like to get the CI checks fixed first.
> 
> 
> 
> Anything I can do to help on that score?

Yes, help would be very welcome. If you can update our Travis configuration via a PR, I’d be glad to review and merge a fix.

**Comment by jparise** [comment]
> @jparise are you able to cut a release with this fix in it by any chance?

[Version 1.13.2](https://github.com/pear/Log/releases/tag/1.13.2) has been released.

**Pull request merged**
