### PR TITLE
Update Pear Exception version and include patch from #19 to fix issue…

### PR DESCRIPTION
**Pull request by seamuslee001**
…s with examples in the autoloader

ping @jparise

### CODE REVIEW

**Review by MikeyMJCO — COMMENTED** [review]
Is there a reason to not just require `1.0.2` rather than 1.0.1 or 1.0.2?

@jparise any thoughts here?

**Comment by seamuslee001** [comment]
@MikeyMJCO so D9.1 explicitly is for v1.0.1 https://github.com/drupal/core-recommended/blob/9.1.x/composer.json#L29 and 9.2.x is v1.0.2 maybe if we did like ^1.0 instead maybe? I just fear if we dropped 1.0.1 there would be build conflicts with 9.1 and lower

**Comment by MikeyMJCO** [comment]
Thanks Seamus - that makes sense!

**Review by jparise — APPROVED** [review]

**Comment by jparise** [comment]
Thanks @seamuslee001!

**Comment by MikeyMJCO** [comment]
Thanks @jparise :-) any chance you could make a release with this change? :-)

**Comment by jparise** [comment]
> Thanks @jparise :-) any chance you could make a release with this change? :-)

Version 1.13.3 has been released.

**Pull request merged**
